---
apiVersion: v1
kind: Service
metadata:
  name: keel
spec:
  type: NodePort
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    app: keel
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keel.$DOMAIN`)
      kind: Rule
      services:
        - name: keel
          port: 9300
      middlewares:
        - name: traefik-compress
          namespace: traefik
  tls:
    secretName: dev-keel-cert-tls
