---
# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
  namespace: monitoring
spec:
  basicAuth:
    secret: prometheus-authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-authsecret
  namespace: monitoring
data:
  users: dHJhZWZpazokMnkkMDUkUlFRQ0gzWUplSllUa2ZkVFkyaGZkZVdIWXlBSTMyUlU2bGFJQ0FTUnV6NG9TSGhWNTJBa0sNCg0K
type: Opaque
---
# Enable gzip compression
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prometheus-compress
  namespace: monitoring
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.dev.custd.com`)
      kind: Rule
      services:
        - name: prometheus-operated
          port: 9090
      middlewares:
        - name: prometheus-auth
          namespace: monitoring
        - name: prometheus-compress
          namespace: monitoring
  tls:
    secretName: dev-prometheus-cert-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.dev.custd.com`)
      kind: Rule
      services:
        - name: prometheus-operator-grafana
          port: 80
      middlewares:
        - name: prometheus-compress
          namespace: monitoring
  tls:
    secretName: dev-prometheus-cert-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alertmanager.dev.custd.com`)
      kind: Rule
      services:
        - name: alertmanager-operated
          port: 9093
      middlewares:
        - name: prometheus-auth
          namespace: monitoring
        - name: prometheus-compress
          namespace: monitoring
  tls:
    secretName: dev-prometheus-cert-tls
