---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-traefik-cert
  namespace: traefik
spec:
  secretName: dev-traefik-cert-tls
  commonName: traefik.$DOMAIN
  dnsNames:
    - traefik.$DOMAIN
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
