---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-lv-example
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: wave-lv-example
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: wave-lv-example
    spec:
      containers:
        - name: wave-lv-example
          image: haakco/stage3-ubuntu-20.04-php7.4-lv
          ports:
            - containerPort: 80
          env:
            - name: GEN_LV_ENV
              value: "TRUE"
            - name: LVENV_APP_NAME
              value: "$APP_NAME"
            - name: LVENV_APP_ENV
              value: "$APP_ENV"
            - name: LVENV_APP_KEY
              value: "$APP_KEY"
            - name: LVENV_APP_DEBUG
              value: "$APP_DEBUG"
            - name: LVENV_APP_LOG_LEVEL
              value: "$APP_LOG_LEVEL"
            - name: LVENV_APP_URL
              value: "https://$DOMAIN_NAME"
            - name: LVENV_DB_CONNECTION
              value: "pgsql"
            - name: LVENV_DB_HOST
              value: "$DB_HOST"
            - name: LVENV_DB_PORT
              value: "5432"
            - name: LVENV_DB_DATABASE
              value: "$DB_NAME"
            - name: LVENV_DB_USERNAME
              value: "$DB_USER"
            - name: LVENV_DB_PASSWORD
              value: "$DB_PASS"
            - name: LVENV_BROADCAST_DRIVER
              value: "log"
            - name: LVENV_CACHE_DRIVER
              value: "redis"
            - name: LVENV_SESSION_DRIVER
              value: "redis"
            - name: LVENV_SESSION_LIFETIME
              value: "9999"
            - name: LVENV_QUEUE_DRIVER
              value: "redis"
            - name: LVENV_REDIS_HOST
              value: "$REDIS_HOST"
            - name: LVENV_REDIS_PASSWORD
              value: "$REDIS_PASS"
            - name: LVENV_REDIS_PORT
              value: "6379"
            - name: LVENV_MAIL_DRIVER
              value: "smtp"
            - name: LVENV_MAIL_HOST
              value: "$MAIL_HOST"
            - name: LVENV_MAIL_PORT
              value: "$MAIL_PORT"
            - name: LVENV_MAIL_USERNAME
              value: "$MAIL_USERNAME"
            - name: LVENV_MAIL_PASSWORD
              value: "$MAIL_PASSWORD"
            - name: LVENV_MAIL_ENCRYPTION
              value: "$MAIL_ENCRYPTION"
            - name: LVENV_PUSHER_APP_ID
              value: ""
            - name: LVENV_PUSHER_APP_KEY
              value: ""
            - name: LVENV_PUSHER_APP_SECRET
              value: ""
            - name: LVENV_REDIS_CLIENT
              value: "phpredis"
            - name: LVENV_JWT_SECRET
              value: "$JWT_SECRET"
            - name: LVENV_PADDLE_VENDOR_ID
              value: ""
            - name: LVENV_PADDLE_VENDOR_AUTH_CODE
              value: ""
            - name: LVENV_PADDLE_ENV
              value: "sandbox"
            - name: LVENV_WAVE_DOCS
              value: "true"
            - name: LVENV_WAVE_DEMO
              value: "true"
            - name: LVENV_WAVE_BAR
              value: "true"
            - name: LVENV_TRUSTED_PROXIES
              value: "$TRUSTED_PROXIES"
            - name: LVENV_ASSET_URL
              value: " "
          volumeMounts:
            - mountPath: /var/www/site
              name: wave-volume
      volumes:
        - name: wave-volume
          hostPath:
            path: $WAVE_DIR
---
apiVersion: v1
kind: Service
metadata:
  name: wave-lv-example
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wave-lv-example
---
# Enable gzip compression
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: wave-traefik-compress
spec:
  compress: { }
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wave-traefik-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`$DOMAIN`, `www.$DOMAIN`)
      kind: Rule
      services:
        - name: wave-lv-example
          port: 80
      middlewares:
        - name: wave-traefik-compress
  tls:
    secretName: dev-wave-cert-prod-tls

