---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-keycloak-cert
spec:
  secretName: dev-keycloak-cert-tls
  commonName: sso.$DOMAIN
  dnsNames:
    - sso.$DOMAIN
    - keycloak.$DOMAIN
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
