---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sso.$DOMAIN`, `keycloak.$DOMAIN`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
      middlewares:
        - name: traefik-compress
          namespace: traefik
  tls:
    secretName: dev-keycloak-cert-tls
