---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $CERT_EMAIL
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - dns01:
        cloudflare:
          email: tutorial@custd.com
          apiTokenSecretRef:
            name: cloudflare-apikey
            key: cloudflare_api_token
